[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

# Enable form detection
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.forms]
  enable = true

# Handle trailing slashes and prevent duplicate content
[[redirects]]
  from = "/blog/"
  to = "/blog"
  status = 301

[[redirects]]
  from = "/about/"
  to = "/about"
  status = 301

[[redirects]]
  from = "/services/"
  to = "/services"
  status = 301

[[redirects]]
  from = "/portfolio/"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/contact/"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/creative/"
  to = "/creative"
  status = 301

# Handle old blog URLs if they exist
[[redirects]]
  from = "/posts"
  to = "/blog"
  status = 301

# Handle any other trailing slash issues
[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
