[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

# Enable form detection
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.forms]
  enable = true
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
