[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173

# Enable form detection
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = false

[build.processing.forms]
  enable = true

# Handle old blog URLs if they exist
[[redirects]]
  from = "/posts"
  to = "/blog"
  status = 301

# SPA fallback - must be last
# This should NOT use force=true as it would intercept asset requests
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
