import post from './post'
import category from './category'
import author from './author'
import serviceImage from './serviceImage'
import servicePageSection from './servicePageSection'
import aboutSection from './aboutSection'
import testimonial from './testimonial'
import logo from './logo'
import teamMember from './teamMember'
import portfolioBrand from './portfolioBrand'
import portfolioItem from './portfolioItem'
import servicesPageImages from '../schemas/servicesPageImages'
import galleryImage from '../schemas/galleryImage'
import creativeCarousel from './creativeCarousel'
import creativePage from './creativePage'
import glassPage from './glassPage'
import glassType from './glassType'
import manufacturingStep from './manufacturingStep'

export const schemaTypes = [post, category, author, serviceImage, servicePageSection, aboutSection, testimonial, logo, teamMember, portfolioBrand, portfolioItem, servicesPageImages, galleryImage, creativeCarousel, creativePage, glassPage, glassType, manufacturingStep]
