import post from './post'
import video from './video'
import category from './category'
import author from './author'
import heroSection from './heroSection'
import service from './service'
import serviceImage from './serviceImage'
import servicePageSection from './servicePageSection'
import aboutSection from './aboutSection'
import testimonial from './testimonial'
import logo from './logo'
import teamMember from './teamMember'
import portfolioBrand from './portfolioBrand'
import portfolioItem from './portfolioItem'
import servicesPageImages from '../schemas/servicesPageImages'
import galleryImage from '../schemas/galleryImage'

export const schemaTypes = [post, video, category, author, heroSection, service, serviceImage, servicePageSection, aboutSection, testimonial, logo, teamMember, portfolioBrand, portfolioItem, servicesPageImages, galleryImage]
